/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author zenni
 */
public class BooksPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BooksPage.class.getName());

    /**
     * Creates new form dashboard
     */
    public BooksPage() {
        initComponents();
        setSize(1293,760);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        FilterBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Profile_icon1 = new javax.swing.JLabel();
        SupportBTN = new javax.swing.JButton();
        LibraryBTN = new javax.swing.JButton();
        MoviesBTN = new javax.swing.JButton();
        NewestBTN = new javax.swing.JButton();
        BooksBTN = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        SearchBTN = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        profileIconBTN = new javax.swing.JButton();
        LogoBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));

        FilterBTN.setBackground(new java.awt.Color(255, 255, 255));
        FilterBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        FilterBTN.setForeground(new java.awt.Color(107, 114, 128));
        FilterBTN.setText("Filter");
        FilterBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        FilterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterBTNActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 560));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        Profile_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/harrypotterHBPcover.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(FilterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272)
                .addComponent(Profile_icon1)
                .addContainerGap(677, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(FilterBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Profile_icon1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(25, 140, 1230, 565);

        SupportBTN.setBackground(new java.awt.Color(232, 241, 253));
        SupportBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SupportBTN.setForeground(new java.awt.Color(17, 24, 39));
        SupportBTN.setText("Support");
        SupportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SupportBTN);
        SupportBTN.setBounds(990, 50, 146, 36);

        LibraryBTN.setBackground(new java.awt.Color(232, 241, 253));
        LibraryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LibraryBTN.setForeground(new java.awt.Color(17, 24, 39));
        LibraryBTN.setText("Library");
        LibraryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LibraryBTN);
        LibraryBTN.setBounds(310, 50, 146, 36);

        MoviesBTN.setBackground(new java.awt.Color(232, 241, 253));
        MoviesBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        MoviesBTN.setForeground(new java.awt.Color(17, 24, 39));
        MoviesBTN.setText("Movies");
        MoviesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(MoviesBTN);
        MoviesBTN.setBounds(650, 50, 146, 36);

        NewestBTN.setBackground(new java.awt.Color(232, 241, 253));
        NewestBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        NewestBTN.setForeground(new java.awt.Color(17, 24, 39));
        NewestBTN.setText("Newest");
        NewestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(NewestBTN);
        NewestBTN.setBounds(820, 50, 146, 36);

        BooksBTN.setBackground(new java.awt.Color(196, 215, 239));
        BooksBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BooksBTN.setForeground(new java.awt.Color(17, 24, 39));
        BooksBTN.setText("Books");
        BooksBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BooksBTN);
        BooksBTN.setBounds(480, 50, 146, 36);

        jTextArea2.setBackground(new java.awt.Color(229, 231, 235));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jTextArea2);
        jTextArea2.setBounds(820, 100, 230, 30);

        SearchBTN.setBackground(new java.awt.Color(229, 231, 235));
        SearchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        SearchBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBTN);
        SearchBTN.setBounds(1050, 100, 40, 30);

        cart.setBackground(new java.awt.Color(255, 255, 255));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        profileIconBTN.setBackground(new java.awt.Color(255, 255, 255));
        profileIconBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        profileIconBTN.setForeground(new java.awt.Color(17, 24, 39));
        profileIconBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N
        profileIconBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconBTNActionPerformed(evt);
            }
        });
        jPanel1.add(profileIconBTN);
        profileIconBTN.setBounds(1180, 10, 90, 90);

        LogoBTN.setBackground(new java.awt.Color(255, 255, 255));
        LogoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        LogoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LogoBTN);
        LogoBTN.setBounds(10, 10, 260, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoBTNActionPerformed
        // TODO add your handling code here:
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoBTNActionPerformed

    private void profileIconBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileIconBTNActionPerformed
        // TODO add your handling code here:
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileIconBTNActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cartActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        ProductPage productPage = new ProductPage();
        productPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void BooksBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksBTNActionPerformed
        // TODO add your handling code here:
        BooksPage booksPage = new BooksPage();
        booksPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksBTNActionPerformed

    private void NewestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestBTNActionPerformed
        // TODO add your handling code here:
        NewestPage newestPage = new NewestPage();
        newestPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestBTNActionPerformed

    private void MoviesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesBTNActionPerformed
        // TODO add your handling code here:
        // Navigate to Profile Page
        BooksPage moviePage = new BooksPage();
        moviePage.setVisible(true);
        this.dispose(); // Close current dashboard
    }//GEN-LAST:event_MoviesBTNActionPerformed

    private void LibraryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryBTNActionPerformed
        // TODO add your handling code here:
        LibraryPage libraryPage = new LibraryPage();
        libraryPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LibraryBTNActionPerformed

    private void SupportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportBTNActionPerformed
        // TODO add your handling code here:
        ProductPage productPage = new ProductPage();
        productPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SupportBTNActionPerformed

    private void FilterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterBTNActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BooksPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BooksBTN;
    private javax.swing.JButton FilterBTN;
    private javax.swing.JButton LibraryBTN;
    private javax.swing.JButton LogoBTN;
    private javax.swing.JButton MoviesBTN;
    private javax.swing.JButton NewestBTN;
    private javax.swing.JLabel Profile_icon1;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton SupportBTN;
    private javax.swing.JButton cart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton profileIconBTN;
    // End of variables declaration//GEN-END:variables
    
}
