/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.ProductDao;
import Model.Product;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class BookPanel extends javax.swing.JPanel {

    /**
     * Creates new form Bookpanel
     */
    public BookPanel() {
        initComponents();
        loadProductsFromDatabase();
    }
    
    private void loadProductsFromDatabase() {
        
        ProductDao dao = new ProductDao();
        List<Product> list = dao.getAll();
        System.out.println("Product size = " + list.size());

        
        DefaultTableModel model = (DefaultTableModel) booktableproduct.getModel();
        model.setRowCount(0);
        
        for(Product p : list){
            model.addRow(new Object[] {p.id, p.name, p.type, p.category });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        booktableproduct = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(null);

        booktableproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "TYPE", "CATEGORY"
            }
        ));
        jScrollPane1.setViewportView(booktableproduct);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1280, 720);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booktableproduct;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
