/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.CartController;
import model.CartItem;
import userdata.UserSession;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;



/**
 *
 * @author Dell
 */
public class Cart extends javax.swing.JFrame {
    private CartController cartController;
    private JPanel contentPanel;
private JSplitPane split;
private int loggedInUserId;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cart.class.getName());

    /**
     * Creates new form Cart
     */
    public Cart() {

    initComponents();
    Cartbox.getInputMap().put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
        "search");
        Cartbox.getActionMap().put("search", new javax.swing.AbstractAction() {
            @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            performSearch();
            }
        });
    cartController = new CartController();
    loggedInUserId = UserSession.getUserId();

    setLocationRelativeTo(null);
    setResizable(true);

    // ✅ Make "Proceed to checkout" behave like a button
    jTextField2.setEditable(false);
    jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            doCheckout();
        }
    });

    
    contentPanel = new JPanel(new BorderLayout());
    contentPanel.setOpaque(false);

    
    jPanel1.remove(Cartbox);
    jPanel1.remove(jPanel4);

    
    Cartbox.removeAll();
    Cartbox.setLayout(new BoxLayout(Cartbox, BoxLayout.Y_AXIS));
    JScrollPane cartScroll = new JScrollPane(Cartbox);
    cartScroll.setBorder(null);

    
    split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, cartScroll, jPanel4);
    split.setResizeWeight(0.50);
    split.setDividerSize(6);
    split.setBorder(null);

    contentPanel.add(split, BorderLayout.CENTER);

    
    contentPanel.setBounds(18, 210, 1240, 430); 
    jPanel1.setLayout(null); 
    jPanel1.add(contentPanel);

    
    SwingUtilities.invokeLater(() -> split.setDividerLocation(0.50));

    
    loadCartItems();
    chkSelectALL.addActionListener(e -> {
    boolean sel = chkSelectALL.isSelected();

    for (java.awt.Component comp : Cartbox.getComponents()) {
        if (!(comp instanceof JPanel)) continue;
        JPanel row = (JPanel) comp;
        Object cbObj = row.getClientProperty("checkBox");
        if (cbObj instanceof JCheckBox) {
            ((JCheckBox) cbObj).setSelected(sel);
        }
    }
    updateTotals();
    });

    pack();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Rentifylogo = new javax.swing.JLabel();
        Librarybutton = new javax.swing.JButton();
        Booksbutton = new javax.swing.JButton();
        Moviesbutton = new javax.swing.JButton();
        Newestbutton = new javax.swing.JButton();
        Supportbutton = new javax.swing.JButton();
        Profileicon = new javax.swing.JLabel();
        CartIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Search_Icon = new javax.swing.JLabel();
        Mainsearchbar = new javax.swing.JTextField();
        pSelectALLBar = new javax.swing.JPanel();
        chkSelectALL = new javax.swing.JCheckBox();
        Cartbox = new javax.swing.JPanel();
        Cartbox1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        HPimg = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Cartbox2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Tslimg = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Cartbox3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Hamletimg = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Cartbox4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        HPimg1 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 250, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        Rentifylogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rentifyohnebg (1).png"))); // NOI18N
        Rentifylogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentifylogoMouseClicked(evt);
            }
        });
        jPanel1.add(Rentifylogo);
        Rentifylogo.setBounds(16, 14, 250, 120);

        Librarybutton.setBackground(new java.awt.Color(232, 241, 253));
        Librarybutton.setText("Library");
        Librarybutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Librarybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LibrarybuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LibrarybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LibrarybuttonMouseExited(evt);
            }
        });
        Librarybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Librarybutton);
        Librarybutton.setBounds(328, 65, 120, 30);

        Booksbutton.setBackground(new java.awt.Color(232, 241, 253));
        Booksbutton.setText("Books");
        Booksbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Booksbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksbuttonMouseExited(evt);
            }
        });
        Booksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Booksbutton);
        Booksbutton.setBounds(490, 65, 120, 30);

        Moviesbutton.setBackground(new java.awt.Color(232, 241, 253));
        Moviesbutton.setText("Movies");
        Moviesbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Moviesbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoviesbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MoviesbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MoviesbuttonMouseExited(evt);
            }
        });
        Moviesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Moviesbutton);
        Moviesbutton.setBounds(651, 65, 120, 30);

        Newestbutton.setBackground(new java.awt.Color(232, 241, 253));
        Newestbutton.setText("Newest");
        Newestbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Newestbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewestbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewestbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewestbuttonMouseExited(evt);
            }
        });
        Newestbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Newestbutton);
        Newestbutton.setBounds(817, 65, 120, 30);

        Supportbutton.setBackground(new java.awt.Color(232, 241, 253));
        Supportbutton.setText("Support");
        Supportbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Supportbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupportbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupportbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupportbuttonMouseExited(evt);
            }
        });
        Supportbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Supportbutton);
        Supportbutton.setBounds(977, 65, 120, 30);

        Profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile icon.png"))); // NOI18N
        Profileicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileiconMouseClicked(evt);
            }
        });
        jPanel1.add(Profileicon);
        Profileicon.setBounds(1162, 35, 60, 60);

        CartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart 25x22.png"))); // NOI18N
        CartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartIconMouseClicked(evt);
            }
        });
        jPanel1.add(CartIcon);
        CartIcon.setBounds(1120, 130, 30, 22);

        jSeparator1.setForeground(new java.awt.Color(209, 213, 219));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 167, 1290, 4);

        jPanel2.setBackground(new java.awt.Color(243, 243, 243));

        Search_Icon.setBackground(new java.awt.Color(243, 243, 243));
        Search_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        Search_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_IconMouseClicked(evt);
            }
        });

        Mainsearchbar.setBackground(new java.awt.Color(243, 243, 243));
        Mainsearchbar.setForeground(new java.awt.Color(107, 114, 128));
        Mainsearchbar.setText("Search in Rentify");
        Mainsearchbar.setBorder(null);
        Mainsearchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MainsearchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MainsearchbarFocusLost(evt);
            }
        });
        Mainsearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainsearchbarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mainsearchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_Icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mainsearchbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(761, 125, 350, 30);

        pSelectALLBar.setBackground(new java.awt.Color(243, 243, 243));
        pSelectALLBar.setPreferredSize(new java.awt.Dimension(35, 40));
        pSelectALLBar.setLayout(new java.awt.BorderLayout());

        chkSelectALL.setBackground(new java.awt.Color(249, 250, 251));
        chkSelectALL.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        chkSelectALL.setForeground(new java.awt.Color(128, 126, 126));
        chkSelectALL.setText("SELECT ALL (ITEM(S))");
        pSelectALLBar.add(chkSelectALL, java.awt.BorderLayout.CENTER);

        jPanel1.add(pSelectALLBar);
        pSelectALLBar.setBounds(118, 183, 578, 30);

        Cartbox.setBackground(new java.awt.Color(255, 255, 255));
        Cartbox.setLayout(new javax.swing.BoxLayout(Cartbox, javax.swing.BoxLayout.Y_AXIS));

        Cartbox1.setBackground(new java.awt.Color(255, 255, 255));
        Cartbox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Cartbox1.setPreferredSize(new java.awt.Dimension(511, 148));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        HPimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Johnwickposter.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(HPimg, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HPimg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Harry Potter ");

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("No Brand");

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("4 iems(s) left");

        jLabel4.setText("Rs.2199");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("1");

        jButton2.setText("+");

        jButton7.setText("-");

        javax.swing.GroupLayout Cartbox1Layout = new javax.swing.GroupLayout(Cartbox1);
        Cartbox1.setLayout(Cartbox1Layout);
        Cartbox1Layout.setHorizontalGroup(
            Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cartbox1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Cartbox1Layout.createSequentialGroup()
                        .addGroup(Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        Cartbox1Layout.setVerticalGroup(
            Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox1Layout.createSequentialGroup()
                .addGroup(Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cartbox1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Cartbox1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Cartbox1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Cartbox1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(Cartbox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cartbox1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Cartbox1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Cartbox.add(Cartbox1);

        Cartbox2.setBackground(new java.awt.Color(255, 255, 255));
        Cartbox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        Tslimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/harrypotterHBPcover.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Tslimg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tslimg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("The Secret Library");

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("No Brand");

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("5 iems(s) left");

        jLabel9.setText("Rs.1499");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("1");

        jButton8.setText("-");

        jButton10.setText("+");

        javax.swing.GroupLayout Cartbox2Layout = new javax.swing.GroupLayout(Cartbox2);
        Cartbox2.setLayout(Cartbox2Layout);
        Cartbox2Layout.setHorizontalGroup(
            Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jCheckBox2)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cartbox2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(Cartbox2Layout.createSequentialGroup()
                        .addGroup(Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Cartbox2Layout.setVerticalGroup(
            Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jCheckBox2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Cartbox2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox2Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGroup(Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cartbox2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(Cartbox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );

        Cartbox.add(Cartbox2);

        Cartbox3.setBackground(new java.awt.Color(255, 255, 255));
        Cartbox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        Hamletimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/harrypotterHBPcover.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Hamletimg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hamletimg, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Hamlet");

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("ebook");

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("No Brand");

        jLabel15.setText("Rs.1499");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("1");

        jButton9.setText("-");

        jButton11.setText("+");

        javax.swing.GroupLayout Cartbox3Layout = new javax.swing.GroupLayout(Cartbox3);
        Cartbox3.setLayout(Cartbox3Layout);
        Cartbox3Layout.setHorizontalGroup(
            Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cartbox3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(Cartbox3Layout.createSequentialGroup()
                                .addGroup(Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Cartbox3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addGroup(Cartbox3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addGap(58, 58, 58))))
        );
        Cartbox3Layout.setVerticalGroup(
            Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox3)
                .addGap(57, 57, 57))
            .addGroup(Cartbox3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox3Layout.createSequentialGroup()
                        .addGroup(Cartbox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(23, 23, 23))))
        );

        Cartbox.add(Cartbox3);

        Cartbox4.setBackground(new java.awt.Color(255, 255, 255));
        Cartbox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        HPimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/harrypotterHBPcover.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(HPimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HPimg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Harry Potter ");

        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("No Brand");

        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("4 iems(s) left");

        jLabel26.setText("Rs.2199");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("1");

        jButton3.setText("+");

        jButton12.setText("-");

        javax.swing.GroupLayout Cartbox4Layout = new javax.swing.GroupLayout(Cartbox4);
        Cartbox4.setLayout(Cartbox4Layout);
        Cartbox4Layout.setHorizontalGroup(
            Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cartbox4Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Cartbox4Layout.createSequentialGroup()
                        .addGroup(Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(165, 165, 165)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        Cartbox4Layout.setVerticalGroup(
            Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cartbox4Layout.createSequentialGroup()
                .addGroup(Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cartbox4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Cartbox4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jCheckBox4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(Cartbox4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Cartbox4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGroup(Cartbox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cartbox4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cartbox4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Cartbox4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cartbox.add(Cartbox4);

        jPanel1.add(Cartbox);
        Cartbox.setBounds(18, 225, 720, 624);

        jPanel4.setBackground(new java.awt.Color(232, 241, 253));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Order Summary");

        jLabel17.setText("0 items");

        jLabel18.setText("Shipping Fee");

        jLabel20.setText("Rs.0");

        jTextField1.setBackground(new java.awt.Color(248, 248, 248));
        jTextField1.setForeground(new java.awt.Color(174, 156, 156));
        jTextField1.setText("Enter Voucher Code");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(13, 106, 210));
        jButton1.setText("APPLY");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Total");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("          Rs = 0");

        jTextField2.setBackground(new java.awt.Color(13, 106, 210));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("PROCEED TO CHECKOUT(0)");

        jLabel19.setText("Items");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jTextField1)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(169, 169, 169)))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(854, 183, 394, 374);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean containsText(java.awt.Component comp, String text) {
 
    if (comp instanceof javax.swing.JLabel) {
        String labelText = ((javax.swing.JLabel) comp).getText();
        if (labelText != null && labelText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.JButton) {
        String btnText = ((javax.swing.JButton) comp).getText();
        if (btnText != null && btnText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.text.JTextComponent) {
        String fieldText = ((javax.swing.text.JTextComponent) comp).getText();
        if (fieldText != null && fieldText.toLowerCase().contains(text)) {
            return true;
        }
    }

    
    if (comp instanceof java.awt.Container) {
        for (java.awt.Component child : ((java.awt.Container) comp).getComponents()) {
            if (containsText(child, text)) {
                return true;
            }
        }
    }
    return false;
}
    private void performSearch() {
    String text = Mainsearchbar.getText().trim().toLowerCase();
    boolean showAll = text.isEmpty();

    for (java.awt.Component comp : Cartbox.getComponents()) {
        boolean visible = showAll;

        if (!showAll) {
            
            visible = containsText(comp, text);
        }
        comp.setVisible(visible);
    }

    Cartbox.revalidate();
    Cartbox.repaint();
}
    private void LibrarybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarybuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Library");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_LibrarybuttonActionPerformed

    private void BooksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Books");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);
    }//GEN-LAST:event_BooksbuttonActionPerformed

    private void MoviesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Movies");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);
    }//GEN-LAST:event_MoviesbuttonActionPerformed

    private void NewestbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Newest");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_NewestbuttonActionPerformed

    private void SupportbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Support");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_SupportbuttonActionPerformed

    private void MainsearchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MainsearchbarFocusGained
        if (Mainsearchbar.getText().equals("Search in Rentify")) {
            Mainsearchbar.setText("");
            Mainsearchbar.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_MainsearchbarFocusGained

    private void MainsearchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MainsearchbarFocusLost
        if (Mainsearchbar.getText().trim().isEmpty()) {
            Mainsearchbar.setText("Search in Rentify");
            Mainsearchbar.setForeground(new java.awt.Color(107, 114, 128));
        }
    }//GEN-LAST:event_MainsearchbarFocusLost

    private void MainsearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainsearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainsearchbarActionPerformed

    private void CartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartIconMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        Cart cr = new Cart();
        cr.setVisible(true);
        cr.setLocation(loc);
        this.dispose();
    }//GEN-LAST:event_CartIconMouseClicked

    private void LibrarybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybuttonMouseEntered
        // TODO add your handling code here:
        Librarybutton.setBackground(new java.awt.Color(52, 115, 196));
        Librarybutton.setForeground(java.awt.Color.WHITE);
        Librarybutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Librarybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LibrarybuttonMouseEntered

    private void LibrarybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybuttonMouseExited
        // TODO add your handling code here:
        Librarybutton.setBackground(new java.awt.Color(232,241,253));
        Librarybutton.setForeground(new java.awt.Color(17,24,39));
        Librarybutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_LibrarybuttonMouseExited

    private void BooksbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksbuttonMouseEntered
        // TODO add your handling code here:
        Booksbutton.setBackground(new java.awt.Color(52, 115, 196));
        Booksbutton.setForeground(java.awt.Color.WHITE);
        Booksbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Booksbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BooksbuttonMouseEntered

    private void BooksbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksbuttonMouseExited
        // TODO add your handling code here:
        Booksbutton.setBackground(new java.awt.Color(232,241,253));
        Booksbutton.setForeground(new java.awt.Color(17,24,39));
        Booksbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_BooksbuttonMouseExited

    private void MoviesbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesbuttonMouseEntered
        // TODO add your handling code here:
        Moviesbutton.setBackground(new java.awt.Color(52, 115, 196));
        Moviesbutton.setForeground(java.awt.Color.WHITE);
        Moviesbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Moviesbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MoviesbuttonMouseEntered

    private void MoviesbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesbuttonMouseExited
        // TODO add your handling code here:
        Moviesbutton.setBackground(new java.awt.Color(232,241,253));
        Moviesbutton.setForeground(new java.awt.Color(17,24,39));
        Moviesbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_MoviesbuttonMouseExited

    private void NewestbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestbuttonMouseEntered
        // TODO add your handling code here:
        Newestbutton.setBackground(new java.awt.Color(52, 115, 196));
        Newestbutton.setForeground(java.awt.Color.WHITE);
        Newestbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Newestbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NewestbuttonMouseEntered

    private void NewestbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestbuttonMouseExited
        // TODO add your handling code here:
        Newestbutton.setBackground(new java.awt.Color(232,241,253));
        Newestbutton.setForeground(new java.awt.Color(17,24,39));
        Newestbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_NewestbuttonMouseExited

    private void SupportbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportbuttonMouseEntered
        // TODO add your handling code here:
        Supportbutton.setBackground(new java.awt.Color(52, 115, 196));
        Supportbutton.setForeground(java.awt.Color.WHITE);
        Supportbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Supportbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SupportbuttonMouseEntered

    private void SupportbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportbuttonMouseExited
        // TODO add your handling code here:
        Supportbutton.setBackground(new java.awt.Color(232,241,253));
        Supportbutton.setForeground(new java.awt.Color(17,24,39));
        Supportbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_SupportbuttonMouseExited

    private void RentifylogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentifylogoMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        HomePage hm = new HomePage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_RentifylogoMouseClicked

    private void LibrarybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        LibraryPage hm = new LibraryPage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LibrarybuttonMouseClicked

    private void BooksbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksbuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        BooksPage hm = new BooksPage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksbuttonMouseClicked

    private void MoviesbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesbuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        MoviePage hm = new MoviePage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MoviesbuttonMouseClicked

    private void NewestbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestbuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        NewestPage hm = new NewestPage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestbuttonMouseClicked

    private void SupportbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportbuttonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SupportbuttonMouseClicked

    private void ProfileiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileiconMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        UserDashboard hm = new UserDashboard();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfileiconMouseClicked

    private void Search_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_IconMouseClicked
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_Search_IconMouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if (jTextField1.getText().equals("Enter Voucher Code")) {
            jTextField1.setText("");
            jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().trim().isEmpty()) {
            jTextField1.setText("Enter Voucher Code");
            jTextField1.setForeground(new java.awt.Color(107, 114, 128));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cart().setVisible(true));
    }
    
    
    
    
    private void doCheckout() {
    if (loggedInUserId == -1) {
        JOptionPane.showMessageDialog(this, "Please login again.");
        return;
    }

    // build list of selected items
    java.util.List<CartItem> selectedItems = new java.util.ArrayList<>();

    for (java.awt.Component comp : Cartbox.getComponents()) {
        if (!(comp instanceof JPanel)) continue;
        JPanel row = (JPanel) comp;

        Object cbObj   = row.getClientProperty("checkBox");
        Object itemObj = row.getClientProperty("cartItem");
        Object qtyObj  = row.getClientProperty("qtyLabel");
        if (!(cbObj instanceof JCheckBox) || !(itemObj instanceof CartItem) || !(qtyObj instanceof JLabel))
            continue;

        JCheckBox cb = (JCheckBox) cbObj;
        CartItem item = (CartItem) itemObj;
        JLabel qtyLabel = (JLabel) qtyObj;

        if (cb.isSelected()) {
            int q = Integer.parseInt(qtyLabel.getText());
            item.setQuantity(q);          // use current quantity in UI
            selectedItems.add(item);
        }
    }

    if (selectedItems.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select at least one item.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Checkout " + selectedItems.size() + " item(s)?",
            "Confirm Checkout",
            JOptionPane.YES_NO_OPTION
    );
    if (confirm != JOptionPane.YES_OPTION) return;

    cartController.checkoutCart(selectedItems, loggedInUserId);

    JOptionPane.showMessageDialog(this, "Checkout successful!");
    loadCartItems();
}

    private void loadCartItems() {

    Cartbox.removeAll();
    if (loggedInUserId == -1) {
        JOptionPane.showMessageDialog(this, "Please login again.");
        dispose();
        return;
    }

    java.util.List<CartItem> cartItems = cartController.getCartItems(loggedInUserId);

    for (CartItem item : cartItems) {
        Cartbox.add(createCartItemPanel(item));
        Cartbox.add(Box.createVerticalStrut(10));
    }

    updateTotals();          
    Cartbox.revalidate();
    Cartbox.repaint();
}

    
   private void formWindowOpened(java.awt.event.WindowEvent evt) {
    chkSelectALL.addActionListener(e -> {
        boolean sel = chkSelectALL.isSelected();
        for (java.awt.Component comp : Cartbox.getComponents()) {
            if (!(comp instanceof JPanel)) continue;
            JPanel row = (JPanel) comp;
            Object cbObj = row.getClientProperty("checkBox");
            if (cbObj instanceof JCheckBox) {
                ((JCheckBox) cbObj).setSelected(sel);
            }
        }
        updateTotals();
    });
}
 
   private javax.swing.JPanel createCartItemPanel(CartItem item) {

    JPanel row = new JPanel(new BorderLayout(15, 10));
    row.setBackground(Color.WHITE);
    row.setBorder(BorderFactory.createLineBorder(new Color(204, 204, 204)));
    row.setMaximumSize(new Dimension(950, 150));
    row.setPreferredSize(new Dimension(950, 150));

    // LEFT: checkbox + image
    JPanel left = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 20));
    left.setBackground(Color.WHITE);

    JCheckBox cb = new JCheckBox();
    cb.setBackground(Color.WHITE);

    JLabel img = new JLabel();
    img.setPreferredSize(new Dimension(99, 122));
    try {
        img.setIcon(new ImageIcon(getClass().getResource(item.getImage())));
    } catch (Exception e) {
        img.setText("No Image");
    }

    left.add(cb);
    left.add(img);
    row.add(left, BorderLayout.WEST);

    // CENTER: name + brand + type
    JPanel center = new JPanel();
    center.setBackground(Color.WHITE);
    center.setLayout(new BoxLayout(center, BoxLayout.Y_AXIS));
    center.setBorder(new EmptyBorder(20, 0, 0, 0));

    JLabel name = new JLabel(item.getItemName());              // ✅ title from DB
    name.setFont(new Font("Segoe UI", Font.BOLD, 12));

    JLabel brand = new JLabel("No Brand");
    brand.setForeground(new Color(153, 153, 153));

    JLabel type = new JLabel(item.getItemType() + " | " + item.getActionType());  // ✅ type+action
    type.setForeground(new Color(153, 153, 153));

    center.add(name);
    center.add(Box.createVerticalStrut(8));
    center.add(brand);
    center.add(Box.createVerticalStrut(4));
    center.add(type);

    row.add(center, BorderLayout.CENTER);

    // ... center panel as you already have ...

    JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT, 15, 45));
    right.setBackground(Color.WHITE);

    JLabel price = new JLabel("Rs." + item.getPrice());
    JButton minus = new JButton("-");
    JLabel qty = new JLabel(String.valueOf(item.getQuantity()));
    qty.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    JButton plus = new JButton("+");
    JButton removeBtn = new JButton("Remove");

    right.add(price);
    right.add(minus);
    right.add(qty);
    right.add(plus);
    right.add(removeBtn);
    row.add(right, BorderLayout.EAST);

    row.putClientProperty("cartItem", item);
    row.putClientProperty("checkBox", cb);
    row.putClientProperty("qtyLabel", qty);

    cb.addActionListener(e -> updateTotals());
    plus.addActionListener(e -> {
    int q = Integer.parseInt(qty.getText());
    q++;
    qty.setText(String.valueOf(q));
    cartController.updateCartQuantity(item.getCartId(), q);
    updateTotals();
    });
    minus.addActionListener(e -> {
    int q = Integer.parseInt(qty.getText());
    if (q > 1) {
        q--;
        qty.setText(String.valueOf(q));
        cartController.updateCartQuantity(item.getCartId(), q);
        updateTotals();
    }
});
    minus.addActionListener(e -> {
        int q = Integer.parseInt(qty.getText());
        if (q > 1) {
            q--;
            qty.setText(String.valueOf(q));
            cartController.updateCartQuantity(item.getCartId(), q);
            updateTotals();
        }
    });
    removeBtn.addActionListener(e -> {
        cartController.removeItemFromCart(item.getCartId());
        loadCartItems();
    });

    return row;
}
   private void updateTotals() {
    double total = 0.0;
    int selectedCount = 0;
    boolean hasBuy = false;

    for (java.awt.Component comp : Cartbox.getComponents()) {
        if (!(comp instanceof JPanel)) continue;
        JPanel row = (JPanel) comp;

        Object cbObj   = row.getClientProperty("checkBox");
        Object itemObj = row.getClientProperty("cartItem");
        Object qtyObj  = row.getClientProperty("qtyLabel");
        if (!(cbObj instanceof JCheckBox) || !(itemObj instanceof CartItem) || !(qtyObj instanceof JLabel))
            continue;

        JCheckBox cb   = (JCheckBox) cbObj;
        CartItem item  = (CartItem) itemObj;
        JLabel qtyLabel = (JLabel) qtyObj;

        if (cb.isSelected()) {
            int q = Integer.parseInt(qtyLabel.getText());
            total += item.getPrice() * q;
            selectedCount++;

            if ("BUY".equalsIgnoreCase(item.getActionType())) {
                hasBuy = true;
            }
        }
    }

    double shipping = hasBuy ? 39.0 : 0.0;

    jLabel17.setText(selectedCount + " items");          // ✅ only selected
    jLabel20.setText("Rs." + shipping);                  // Shipping Fee
    jLabel22.setText("Rs " + (total + shipping));        // Total incl. shipping
    jTextField2.setText("PROCEED TO CHECKOUT(" + selectedCount + ")");
}   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booksbutton;
    private javax.swing.JLabel CartIcon;
    private javax.swing.JPanel Cartbox;
    private javax.swing.JPanel Cartbox1;
    private javax.swing.JPanel Cartbox2;
    private javax.swing.JPanel Cartbox3;
    private javax.swing.JPanel Cartbox4;
    private javax.swing.JLabel HPimg;
    private javax.swing.JLabel HPimg1;
    private javax.swing.JLabel Hamletimg;
    private javax.swing.JButton Librarybutton;
    private javax.swing.JTextField Mainsearchbar;
    private javax.swing.JButton Moviesbutton;
    private javax.swing.JButton Newestbutton;
    private javax.swing.JLabel Profileicon;
    private javax.swing.JLabel Rentifylogo;
    private javax.swing.JLabel Search_Icon;
    private javax.swing.JButton Supportbutton;
    private javax.swing.JLabel Tslimg;
    private javax.swing.JCheckBox chkSelectALL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pSelectALLBar;
    // End of variables declaration//GEN-END:variables
}
