/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Point;
import javax.swing.JPanel;

/**
 *
 * @author zenni
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form dashboard
     */
    public HomePage() {
        initComponents();
        setSize(1293,760);
        
        controller.HomepageController controller = new controller.HomepageController(this);
        
        

        controller.loadAllProducts();
        jTextArea2.getInputMap().put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
        "search");
        jTextArea2.getActionMap().put("search", new javax.swing.AbstractAction() {
            @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            performSearch();
            }
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SupportBTN = new javax.swing.JButton();
        LibraryBTN = new javax.swing.JButton();
        MoviesBTN = new javax.swing.JButton();
        NewestBTN = new javax.swing.JButton();
        BooksBTN = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        SearchBTN = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        homePanelReal = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        logoBTN = new javax.swing.JLabel();
        profileBTN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        SupportBTN.setBackground(new java.awt.Color(232, 241, 253));
        SupportBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SupportBTN.setForeground(new java.awt.Color(17, 24, 39));
        SupportBTN.setText("Support");
        SupportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SupportBTN);
        SupportBTN.setBounds(990, 50, 146, 36);

        LibraryBTN.setBackground(new java.awt.Color(232, 241, 253));
        LibraryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LibraryBTN.setForeground(new java.awt.Color(17, 24, 39));
        LibraryBTN.setText("Library");
        LibraryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LibraryBTN);
        LibraryBTN.setBounds(310, 50, 146, 36);

        MoviesBTN.setBackground(new java.awt.Color(232, 241, 253));
        MoviesBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        MoviesBTN.setForeground(new java.awt.Color(17, 24, 39));
        MoviesBTN.setText("Movies");
        MoviesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(MoviesBTN);
        MoviesBTN.setBounds(650, 50, 146, 36);

        NewestBTN.setBackground(new java.awt.Color(232, 241, 253));
        NewestBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        NewestBTN.setForeground(new java.awt.Color(17, 24, 39));
        NewestBTN.setText("Newest");
        NewestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(NewestBTN);
        NewestBTN.setBounds(820, 50, 146, 36);

        BooksBTN.setBackground(new java.awt.Color(232, 241, 253));
        BooksBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BooksBTN.setForeground(new java.awt.Color(17, 24, 39));
        BooksBTN.setText("Books");
        BooksBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BooksBTN);
        BooksBTN.setBounds(480, 50, 146, 36);

        jTextArea2.setBackground(new java.awt.Color(229, 231, 235));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jTextArea2);
        jTextArea2.setBounds(820, 100, 230, 30);

        SearchBTN.setBackground(new java.awt.Color(229, 231, 235));
        SearchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        SearchBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBTN);
        SearchBTN.setBounds(1050, 100, 40, 30);

        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.setBorder(null);
        cart.setBorderPainted(false);
        cart.setFocusPainted(false);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        homePanelReal.setBackground(new java.awt.Color(255, 255, 255));
        homePanelReal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));
        jScrollPane2.setViewportView(homePanelReal);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 170, 1250, 530);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("Our products");
        jPanel1.add(title);
        title.setBounds(30, 120, 230, 40);

        logoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        logoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoBTNMouseClicked(evt);
            }
        });
        jPanel1.add(logoBTN);
        logoBTN.setBounds(10, 10, 260, 70);

        profileBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N
        profileBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBTNMouseClicked(evt);
            }
        });
        jPanel1.add(profileBTN);
        profileBTN.setBounds(1180, 10, 85, 85);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean containsText(java.awt.Component comp, String text) {
    // If this component has text (e.g. JLabel, JButton, JTextComponent)
    if (comp instanceof javax.swing.JLabel) {
        String labelText = ((javax.swing.JLabel) comp).getText();
        if (labelText != null && labelText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.JButton) {
        String btnText = ((javax.swing.JButton) comp).getText();
        if (btnText != null && btnText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.text.JTextComponent) {
        String fieldText = ((javax.swing.text.JTextComponent) comp).getText();
        if (fieldText != null && fieldText.toLowerCase().contains(text)) {
            return true;
        }
    }

    // If it's a container (like JPanel), search its children
    if (comp instanceof java.awt.Container) {
        for (java.awt.Component child : ((java.awt.Container) comp).getComponents()) {
            if (containsText(child, text)) {
                return true;
            }
        }
    }
    return false;
}

    private void performSearch() {
    String text = jTextArea2.getText().trim().toLowerCase();
    boolean showAll = text.isEmpty();

    for (java.awt.Component comp : homePanelReal.getComponents()) {
        boolean visible = showAll;

        if (!showAll) {
            // Search in all child components' text
            visible = containsText(comp, text);
        }
        comp.setVisible(visible);
    }

    homePanelReal.revalidate();
    homePanelReal.repaint();
    }
    private void SupportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        SupportPage supportPage = new SupportPage();
        supportPage.setLocation(loc);
        supportPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SupportBTNActionPerformed

    private void LibraryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        LibraryPage libraryPage = new LibraryPage();
        libraryPage.setLocation(loc);
        libraryPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LibraryBTNActionPerformed

    private void MoviesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesBTNActionPerformed
        // TODO add your handling code here:
    // Navigate to Profile Page
        Point loc = this.getLocation();
        MoviePage moviePage = new MoviePage();
        moviePage.setLocation(loc);
        moviePage.setVisible(true);
        this.dispose(); // Close current dashboard

    }//GEN-LAST:event_MoviesBTNActionPerformed

    private void NewestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        NewestPage newestPage = new NewestPage();
        newestPage.setLocation(loc);
        newestPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestBTNActionPerformed

    private void BooksBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        BooksPage booksPage = new BooksPage();
        booksPage.setLocation(loc);
        booksPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        performSearch();
       
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cartActionPerformed

    private void logoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        HomePage homePage = new HomePage();
        homePage.setLocation(loc);
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoBTNMouseClicked

    private void profileBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setLocation(loc);
        userDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BooksBTN;
    private javax.swing.JButton LibraryBTN;
    private javax.swing.JButton MoviesBTN;
    private javax.swing.JButton NewestBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton SupportBTN;
    private javax.swing.JButton cart;
    private javax.swing.JPanel homePanelReal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel logoBTN;
    private javax.swing.JLabel profileBTN;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getProductPanel(){
        return homePanelReal;
    }
}
