/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author zenni
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form dashboard
     */
    public HomePage() {
        initComponents();
        setSize(1293,760);
        pack();                    
        setLocationRelativeTo(null); 
        setVisible(true);
        jTextArea2.getInputMap().put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
        "search");
        jTextArea2.getActionMap().put("search", new javax.swing.AbstractAction() {
            @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            performSearch();
            }
        });
        controller.HomepageController controller = new controller.HomepageController(this);
        
        

        controller.loadAllProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profileIconBTN = new javax.swing.JButton();
        SupportBTN = new javax.swing.JButton();
        LibraryBTN = new javax.swing.JButton();
        MoviesBTN = new javax.swing.JButton();
        NewestBTN = new javax.swing.JButton();
        BooksBTN = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        SearchBTN = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        homePanelReal = new javax.swing.JPanel();
        LogoBTN = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 250, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        profileIconBTN.setBackground(new java.awt.Color(249, 250, 251));
        profileIconBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        profileIconBTN.setForeground(new java.awt.Color(17, 24, 39));
        profileIconBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N
        profileIconBTN.setBorder(null);
        profileIconBTN.setFocusPainted(false);
        profileIconBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileIconBTNActionPerformed(evt);
            }
        });
        jPanel1.add(profileIconBTN);
        profileIconBTN.setBounds(1180, 10, 90, 90);

        SupportBTN.setBackground(new java.awt.Color(232, 241, 253));
        SupportBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SupportBTN.setForeground(new java.awt.Color(17, 24, 39));
        SupportBTN.setText("Support");
        SupportBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupportBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupportBTNMouseExited(evt);
            }
        });
        SupportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SupportBTN);
        SupportBTN.setBounds(990, 50, 146, 36);

        LibraryBTN.setBackground(new java.awt.Color(232, 241, 253));
        LibraryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LibraryBTN.setForeground(new java.awt.Color(17, 24, 39));
        LibraryBTN.setText("Library");
        LibraryBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LibraryBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LibraryBTNMouseExited(evt);
            }
        });
        LibraryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LibraryBTN);
        LibraryBTN.setBounds(310, 50, 146, 36);

        MoviesBTN.setBackground(new java.awt.Color(232, 241, 253));
        MoviesBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        MoviesBTN.setForeground(new java.awt.Color(17, 24, 39));
        MoviesBTN.setText("Movies");
        MoviesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MoviesBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MoviesBTNMouseExited(evt);
            }
        });
        MoviesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(MoviesBTN);
        MoviesBTN.setBounds(650, 50, 146, 36);

        NewestBTN.setBackground(new java.awt.Color(232, 241, 253));
        NewestBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        NewestBTN.setForeground(new java.awt.Color(17, 24, 39));
        NewestBTN.setText("Newest");
        NewestBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewestBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewestBTNMouseExited(evt);
            }
        });
        NewestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(NewestBTN);
        NewestBTN.setBounds(820, 50, 146, 36);

        BooksBTN.setBackground(new java.awt.Color(232, 241, 253));
        BooksBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BooksBTN.setForeground(new java.awt.Color(17, 24, 39));
        BooksBTN.setText("Books");
        BooksBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksBTNMouseExited(evt);
            }
        });
        BooksBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BooksBTN);
        BooksBTN.setBounds(480, 50, 146, 36);

        jTextArea2.setBackground(new java.awt.Color(243, 243, 243));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jTextArea2);
        jTextArea2.setBounds(820, 100, 230, 30);

        SearchBTN.setBackground(new java.awt.Color(243, 243, 243));
        SearchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        SearchBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBTN);
        SearchBTN.setBounds(1050, 100, 40, 30);

        cart.setBackground(new java.awt.Color(249, 250, 251));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.setBorder(null);
        cart.setFocusPainted(false);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        homePanelReal.setBackground(new java.awt.Color(255, 255, 255));
        homePanelReal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));
        jScrollPane2.setViewportView(homePanelReal);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 170, 1250, 530);

        LogoBTN.setBackground(new java.awt.Color(249, 250, 251));
        LogoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        LogoBTN.setBorder(null);
        LogoBTN.setFocusPainted(false);
        LogoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LogoBTN);
        LogoBTN.setBounds(10, 10, 260, 70);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("Our products");
        jPanel1.add(title);
        title.setBounds(30, 120, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean containsText(java.awt.Component comp, String text) {
    // If this component has text (e.g. JLabel, JButton, JTextComponent)
    if (comp instanceof javax.swing.JLabel) {
        String labelText = ((javax.swing.JLabel) comp).getText();
        if (labelText != null && labelText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.JButton) {
        String btnText = ((javax.swing.JButton) comp).getText();
        if (btnText != null && btnText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.text.JTextComponent) {
        String fieldText = ((javax.swing.text.JTextComponent) comp).getText();
        if (fieldText != null && fieldText.toLowerCase().contains(text)) {
            return true;
        }
    }

    // If it's a container (like JPanel), search its children
    if (comp instanceof java.awt.Container) {
        for (java.awt.Component child : ((java.awt.Container) comp).getComponents()) {
            if (containsText(child, text)) {
                return true;
            }
        }
    }
    return false;
}

    private void performSearch() {
    String text = jTextArea2.getText().trim().toLowerCase();
    boolean showAll = text.isEmpty();

    for (java.awt.Component comp : homePanelReal.getComponents()) {
        boolean visible = showAll;

        if (!showAll) {
            // Search in all child components' text
            visible = containsText(comp, text);
        }
        comp.setVisible(visible);
    }

    homePanelReal.revalidate();
    homePanelReal.repaint();
}

    private void SupportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupportBTNActionPerformed

    private void LibraryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        this.dispose();
        LibraryPage libraryPage = new LibraryPage();
        libraryPage.setLocation(loc);
        libraryPage.setVisible(true);
    }//GEN-LAST:event_LibraryBTNActionPerformed

    private void MoviesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesBTNActionPerformed
        // TODO add your handling code here:
    // Navigate to Profile Page
    Point loc = this.getLocation();
        MoviePage moviePage = new MoviePage();
        moviePage.setLocation(loc);
        moviePage.setVisible(true);
        this.dispose(); // Close current dashboard

    }//GEN-LAST:event_MoviesBTNActionPerformed

    private void NewestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        NewestPage newestPage = new NewestPage();
        newestPage.setLocation(loc);
        newestPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestBTNActionPerformed

    private void BooksBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        BooksPage booksPage = new BooksPage();
        booksPage.setLocation(loc);
        booksPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        Cart cr = new Cart();
        cr.setLocation(loc);
        cr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cartActionPerformed

    private void LogoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        HomePage homePage = new HomePage();
        homePage.setLocation(loc);
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoBTNActionPerformed

    private void profileIconBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileIconBTNActionPerformed
                // TODO add your handling code here:
        Point loc = this.getLocation();
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setLocation(loc);
        userDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileIconBTNActionPerformed

    private void LibraryBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibraryBTNMouseEntered
        // TODO add your handling code here:
        LibraryBTN.setBackground(new java.awt.Color(52, 115, 196));
        LibraryBTN.setForeground(java.awt.Color.WHITE);
        LibraryBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        LibraryBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LibraryBTNMouseEntered

    private void LibraryBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibraryBTNMouseExited
        // TODO add your handling code here:
        LibraryBTN.setBackground(new java.awt.Color(232,241,253));
        LibraryBTN.setForeground(new java.awt.Color(17,24,39));
        LibraryBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_LibraryBTNMouseExited

    private void BooksBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksBTNMouseEntered
        // TODO add your handling code here:
        BooksBTN.setBackground(new java.awt.Color(52, 115, 196));
        BooksBTN.setForeground(java.awt.Color.WHITE);
        BooksBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        BooksBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BooksBTNMouseEntered

    private void BooksBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksBTNMouseExited
        // TODO add your handling code here:
        BooksBTN.setBackground(new java.awt.Color(232,241,253));
        BooksBTN.setForeground(new java.awt.Color(17,24,39));
        BooksBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_BooksBTNMouseExited

    private void MoviesBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesBTNMouseEntered
        // TODO add your handling code here:
        MoviesBTN.setBackground(new java.awt.Color(52, 115, 196));
        MoviesBTN.setForeground(java.awt.Color.WHITE);
        MoviesBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        MoviesBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MoviesBTNMouseEntered

    private void MoviesBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesBTNMouseExited
        // TODO add your handling code here:
        MoviesBTN.setBackground(new java.awt.Color(232,241,253));
        MoviesBTN.setForeground(new java.awt.Color(17,24,39));
        MoviesBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_MoviesBTNMouseExited

    private void NewestBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestBTNMouseEntered
        // TODO add your handling code here:
        NewestBTN.setBackground(new java.awt.Color(52, 115, 196));
        NewestBTN.setForeground(java.awt.Color.WHITE);
        NewestBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        NewestBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NewestBTNMouseEntered

    private void NewestBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestBTNMouseExited
        // TODO add your handling code here:
        NewestBTN.setBackground(new java.awt.Color(232,241,253));
        NewestBTN.setForeground(new java.awt.Color(17,24,39));
        NewestBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_NewestBTNMouseExited

    private void SupportBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportBTNMouseEntered
        // TODO add your handling code here:
        SupportBTN.setBackground(new java.awt.Color(52, 115, 196));
        SupportBTN.setForeground(java.awt.Color.WHITE);
        SupportBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        SupportBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SupportBTNMouseEntered

    private void SupportBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportBTNMouseExited
        // TODO add your handling code here:
        SupportBTN.setBackground(new java.awt.Color(232,241,253));
        SupportBTN.setForeground(new java.awt.Color(17,24,39));
        SupportBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_SupportBTNMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BooksBTN;
    private javax.swing.JButton LibraryBTN;
    private javax.swing.JButton LogoBTN;
    private javax.swing.JButton MoviesBTN;
    private javax.swing.JButton NewestBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton SupportBTN;
    private javax.swing.JButton cart;
    private javax.swing.JPanel homePanelReal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton profileIconBTN;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getProductPanel(){
        return homePanelReal;
    }
}
