/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.controller;
import java.awt.Point;
import javax.swing.JOptionPane;
import model.User_model;
import userdata.UserSession;
import userdata.userDao;

/**
 *
 * @author zenni
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private final controller Controller;

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        pack();                    
        setLocationRelativeTo(null); 
        setVisible(true);
        Controller = new controller();
        setSize(1293,760);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Loginbox = new javax.swing.JPanel();
        RentifyIcon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Logintext = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Registerbutton = new javax.swing.JButton();
        Forgotbutton = new javax.swing.JButton();
        Loginbutton = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(249, 250, 251));
        setSize(new java.awt.Dimension(1280, 720));

        Background.setBackground(new java.awt.Color(249, 250, 251));
        Background.setPreferredSize(new java.awt.Dimension(1280, 720));

        Loginbox.setBackground(new java.awt.Color(255, 255, 255));
        Loginbox.setPreferredSize(new java.awt.Dimension(400, 600));

        RentifyIcon.setBackground(new java.awt.Color(255, 255, 255));
        RentifyIcon.setPreferredSize(new java.awt.Dimension(265, 75));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rentify-230.png"))); // NOI18N

        javax.swing.GroupLayout RentifyIconLayout = new javax.swing.GroupLayout(RentifyIcon);
        RentifyIcon.setLayout(RentifyIconLayout);
        RentifyIconLayout.setHorizontalGroup(
            RentifyIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentifyIconLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        RentifyIconLayout.setVerticalGroup(
            RentifyIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentifyIconLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Logintext.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Logintext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logintext.setText("Login");

        Username.setForeground(new java.awt.Color(107, 114, 128));
        Username.setText("Username");
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        Registerbutton.setBackground(new java.awt.Color(232, 241, 253));
        Registerbutton.setText("Register");
        Registerbutton.setPreferredSize(new java.awt.Dimension(116, 29));
        Registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbuttonActionPerformed(evt);
            }
        });

        Forgotbutton.setBackground(new java.awt.Color(232, 241, 253));
        Forgotbutton.setText("Forgot");
        Forgotbutton.setPreferredSize(new java.awt.Dimension(116, 29));
        Forgotbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotbuttonActionPerformed(evt);
            }
        });

        Loginbutton.setBackground(new java.awt.Color(13, 106, 210));
        Loginbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        Loginbutton.setText("Login");
        Loginbutton.setPreferredSize(new java.awt.Dimension(319, 42));
        Loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbuttonActionPerformed(evt);
            }
        });

        Password.setForeground(new java.awt.Color(107, 114, 128));
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout LoginboxLayout = new javax.swing.GroupLayout(Loginbox);
        Loginbox.setLayout(LoginboxLayout);
        LoginboxLayout.setHorizontalGroup(
            LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginboxLayout.createSequentialGroup()
                .addGroup(LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginboxLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(RentifyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginboxLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Logintext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginboxLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginboxLayout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginboxLayout.createSequentialGroup()
                        .addComponent(Registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(Forgotbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginboxLayout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(38, 38, 38)))
        );
        LoginboxLayout.setVerticalGroup(
            LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginboxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(RentifyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logintext)
                .addGap(118, 118, 118)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forgotbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(LoginboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginboxLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );

        jLabel2.setBackground(new java.awt.Color(249, 250, 251));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/administrator-icon.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(Loginbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Loginbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, 734, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void RegisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbuttonActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        registration registry = new registration();
        registry.setLocation(loc);
        registry.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterbuttonActionPerformed

    private void ForgotbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgotbuttonActionPerformed

    private void LoginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbuttonActionPerformed
        // TODO add your handling code here:
    String username = Username.getText();
    String password = new String(Password.getPassword());   // or getText()

    // Build model for DAO
    User_model input = new User_model();
    input.setUsername(username);
    input.setPassword(password);

    userDao dao = new userDao();

    // Get full user (with user_id) from DB
    User_model loggedIn = dao.loginAndGetUser(input);

    if (loggedIn != null) {
        // ✅ Save to session
        UserSession.setCurrentUser(loggedIn);
        System.out.println("Logged in userId = " + UserSession.getUserId());

        Point loc = this.getLocation();
        HomePage home = new HomePage();
        home.setLocation(loc);
        home.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid username or password!");
    }
    }//GEN-LAST:event_LoginbuttonActionPerformed

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        // TODO add your handling code here:
        if (Username.getText().equals("Username")){
            Username.setText("");
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        // TODO add your handling code here:
        if (Username.getText().equals("")){
            Username.setText("Username");
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // TODO add your handling code here:      
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        AdminLogin ad = new AdminLogin();
        ad.setLocation(loc);
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Forgotbutton;
    private javax.swing.JPanel Loginbox;
    private javax.swing.JButton Loginbutton;
    private javax.swing.JLabel Logintext;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Registerbutton;
    private javax.swing.JPanel RentifyIcon;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}