/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author zenni
 */
public class ProductPagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPagePanel
     */
    public ProductPagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImage = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        productSynopsis = new javax.swing.JLabel();

        setLayout(null);
        add(productImage);
        productImage.setBounds(50, 20, 150, 140);

        productName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        productName.setForeground(new java.awt.Color(51, 51, 51));
        productName.setText("Transformers");
        add(productName);
        productName.setBounds(230, 20, 530, 32);

        productPrice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        productPrice.setForeground(new java.awt.Color(255, 51, 51));
        productPrice.setText("Rs. 999");
        add(productPrice);
        productPrice.setBounds(50, 170, 70, 22);

        productSynopsis.setText("Synopsis of the product");
        add(productSynopsis);
        productSynopsis.setBounds(230, 80, 510, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productImage;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel productSynopsis;
    // End of variables declaration//GEN-END:variables
}
