/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import model.ProductModel;

/**
 *
 * @author zenni
 */
public class ProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form productPanel
     */
    public ProductPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productImage = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();

        setLayout(null);
        add(productImage);
        productImage.setBounds(0, 0, 150, 140);

        productName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productName.setForeground(new java.awt.Color(51, 51, 51));
        productName.setText("Transformers");
        add(productName);
        productName.setBounds(0, 150, 150, 25);

        productPrice.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        productPrice.setForeground(new java.awt.Color(255, 51, 51));
        productPrice.setText("Rs. 999");
        add(productPrice);
        productPrice.setBounds(0, 210, 51, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel productImage;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    // End of variables declaration//GEN-END:variables
    /**public void addProductListener(ActionListener listener) {
        addProduct.addActionListener(listener);
    }**/
    public void setProduct(ProductModel product){
        
        productName.setText(product.getProductName());
        productPrice.setText("Rs." + product.getProductPrice());
        
        ImageIcon icon = new ImageIcon(product.getProductImage());
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        productImage.setIcon(new ImageIcon(img));
    }
    public javax.swing.JLabel getProductImage() {
        return productImage;
    }
    
    public javax.swing.JLabel getProductName() {
        return productName;
    }
    
    public javax.swing.JLabel getProductPrice() {
        return productPrice;
    }

}
