/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;



/**
 *
 * @author Dell
 */
public class PurchaseHistory extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PurchaseHistory.class.getName());


    /**
     * Creates new form PurchaseHistory
     */
  
    public PurchaseHistory() {
    initComponents();

    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rentifylogo = new javax.swing.JLabel();
        Librarybutton = new javax.swing.JButton();
        Booksbutton = new javax.swing.JButton();
        Moviesbutton = new javax.swing.JButton();
        Newestbutton = new javax.swing.JButton();
        Supportbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rentifylogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Rentifylogo.png"))); // NOI18N
        getContentPane().add(Rentifylogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        Librarybutton.setBackground(new java.awt.Color(232, 241, 253));
        Librarybutton.setText("Library");
        Librarybutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Librarybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Librarybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 51, 120, 30));

        Booksbutton.setBackground(new java.awt.Color(232, 241, 253));
        Booksbutton.setText("Books");
        Booksbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Booksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Booksbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 51, 120, 30));

        Moviesbutton.setBackground(new java.awt.Color(232, 241, 253));
        Moviesbutton.setText("Movies");
        Moviesbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Moviesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Moviesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 51, 120, 30));

        Newestbutton.setBackground(new java.awt.Color(232, 241, 253));
        Newestbutton.setText("Newest");
        Newestbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Newestbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Newestbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 51, 120, 30));

        Supportbutton.setBackground(new java.awt.Color(232, 241, 253));
        Supportbutton.setText("Support");
        Supportbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Supportbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Supportbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 51, 120, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1140, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LibrarybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarybuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Library");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_LibrarybuttonActionPerformed

    private void BooksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Books");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);
    }//GEN-LAST:event_BooksbuttonActionPerformed

    private void MoviesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Movies");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);
    }//GEN-LAST:event_MoviesbuttonActionPerformed

    private void NewestbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Newest");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_NewestbuttonActionPerformed

    private void SupportbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Support");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_SupportbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PurchaseHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booksbutton;
    private javax.swing.JButton Librarybutton;
    private javax.swing.JButton Moviesbutton;
    private javax.swing.JButton Newestbutton;
    private javax.swing.JLabel Rentifylogo;
    private javax.swing.JButton Supportbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
