/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.regex.Pattern;
import java.awt.Color;
import java.awt.Point;
import javax.swing.BorderFactory;





/**
 *
 * @author Dell
 */
public class RentalDate extends javax.swing.JFrame {
    
     private TableRowSorter<DefaultTableModel> sorter;
     private boolean expiryAsc = true;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalDate.class.getName());

    private void loadSampleData() {
    DefaultTableModel model = (DefaultTableModel) rentalTable.getModel();
    model.setRowCount(0);

    model.addRow(new Object[]{"Harry Potter", "11 Nov 2025", "03 Jan 2026", "Active"});
    model.addRow(new Object[]{"The Secret Library", "11 Nov 2025", "07 Jan 2026", "Active"});
    model.addRow(new Object[]{"Hamlet", "16 Nov 2025", "20 Nov 2025", "Returned"});
    model.addRow(new Object[]{"John Wick", "17 Nov 2025", "25 Nov 2025", "Expired"});
}

    private void performSearch() {
    if (sorter == null) return;

    String q = Mainsearchbar.getText().trim();

    // placeholder or empty => show all
    if (q.isEmpty() || q.equalsIgnoreCase("Search in Rentify")) {
        sorter.setRowFilter(null);
        return;
    }

    // Search in column 0 (Rented Items)
    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(q), 0));
}

    /**
     * Creates new form RentalDate
     */
    public RentalDate() {
        initComponents();
        Mainsearchbar.getInputMap().put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
        "search");
        Mainsearchbar.getActionMap().put("search", new javax.swing.AbstractAction() {
            @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            performSearch();
            }
        });
        
        loadSampleData();

    DefaultTableModel model = (DefaultTableModel) rentalTable.getModel();
    sorter = new TableRowSorter<>(model);
    rentalTable.setRowSorter(sorter);

    statuscombobox.setSelectedItem("All");
}
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Rentifylogo = new javax.swing.JLabel();
        Librarybutton = new javax.swing.JButton();
        Booksbutton = new javax.swing.JButton();
        Moviesbutton = new javax.swing.JButton();
        Newestbutton = new javax.swing.JButton();
        Supportbutton = new javax.swing.JButton();
        Profileicon = new javax.swing.JLabel();
        mainsearchpanel = new javax.swing.JPanel();
        Search_Icon = new javax.swing.JLabel();
        Mainsearchbar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        scrltable = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentalTable = new javax.swing.JTable();
        sortButton = new javax.swing.JButton();
        statuscombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Background.setBackground(new java.awt.Color(249, 250, 251));
        Background.setPreferredSize(new java.awt.Dimension(1280, 720));

        Rentifylogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rentifyohnebg (1).png"))); // NOI18N
        Rentifylogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentifylogoMouseClicked(evt);
            }
        });

        Librarybutton.setBackground(new java.awt.Color(232, 241, 253));
        Librarybutton.setText("Library");
        Librarybutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Librarybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LibrarybuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LibrarybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LibrarybuttonMouseExited(evt);
            }
        });
        Librarybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrarybuttonActionPerformed(evt);
            }
        });

        Booksbutton.setBackground(new java.awt.Color(232, 241, 253));
        Booksbutton.setText("Books");
        Booksbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Booksbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksbuttonMouseExited(evt);
            }
        });
        Booksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksbuttonActionPerformed(evt);
            }
        });

        Moviesbutton.setBackground(new java.awt.Color(232, 241, 253));
        Moviesbutton.setText("Movies");
        Moviesbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Moviesbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoviesbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MoviesbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MoviesbuttonMouseExited(evt);
            }
        });
        Moviesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesbuttonActionPerformed(evt);
            }
        });

        Newestbutton.setBackground(new java.awt.Color(232, 241, 253));
        Newestbutton.setText("Newest");
        Newestbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Newestbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewestbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewestbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewestbuttonMouseExited(evt);
            }
        });
        Newestbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestbuttonActionPerformed(evt);
            }
        });

        Supportbutton.setBackground(new java.awt.Color(232, 241, 253));
        Supportbutton.setText("Support");
        Supportbutton.setPreferredSize(new java.awt.Dimension(146, 36));
        Supportbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupportbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupportbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupportbuttonMouseExited(evt);
            }
        });
        Supportbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportbuttonActionPerformed(evt);
            }
        });

        Profileicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile icon.png"))); // NOI18N
        Profileicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileiconMouseClicked(evt);
            }
        });

        mainsearchpanel.setBackground(new java.awt.Color(243, 243, 243));
        mainsearchpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainsearchpanelMouseClicked(evt);
            }
        });

        Search_Icon.setBackground(new java.awt.Color(243, 243, 243));
        Search_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N

        Mainsearchbar.setBackground(new java.awt.Color(243, 243, 243));
        Mainsearchbar.setForeground(new java.awt.Color(107, 114, 128));
        Mainsearchbar.setText("Search in Rentify");
        Mainsearchbar.setBorder(null);
        Mainsearchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MainsearchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MainsearchbarFocusLost(evt);
            }
        });
        Mainsearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainsearchbarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainsearchpanelLayout = new javax.swing.GroupLayout(mainsearchpanel);
        mainsearchpanel.setLayout(mainsearchpanelLayout);
        mainsearchpanelLayout.setHorizontalGroup(
            mainsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainsearchpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mainsearchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainsearchpanelLayout.setVerticalGroup(
            mainsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainsearchpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_Icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mainsearchbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBar(null);

        rentalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Harry Potter", "11 Nov, 2025", "3 Jan, 2026", "Active "},
                {"The Secret Library", "11 Nov, 2025", "7 Jan, 2026", "Active "},
                {"Hamlet", "16 Nov, 2025", "Returned ", " Returned "},
                {"John Wick", "17 Nov, 2025", "Expired", "Expired "}
            },
            new String [] {
                "Rented Items", "Rented on", "Expiry date", "Status"
            }
        ));
        rentalTable.setRowHeight(85);
        rentalTable.setShowGrid(true);
        jScrollPane1.setViewportView(rentalTable);

        sortButton.setText("Sort");
        sortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortButtonActionPerformed(evt);
            }
        });

        statuscombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All ", "Active ", "Returned ", "Expired", " " }));
        statuscombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuscomboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(statuscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sortButton)
                .addGap(111, 111, 111))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sortButton)
                    .addComponent(statuscombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        scrltable.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrltable)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrltable)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainsearchpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Rentifylogo)
                        .addGap(62, 62, 62)
                        .addComponent(Librarybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Booksbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Moviesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Newestbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Supportbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Profileicon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rentifylogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Profileicon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Librarybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Booksbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Moviesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Newestbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Supportbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9)
                .addComponent(mainsearchpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        getContentPane().add(Background);
        Background.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LibrarybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrarybuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Library");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_LibrarybuttonActionPerformed

    private void BooksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Books");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);
    }//GEN-LAST:event_BooksbuttonActionPerformed

    private void MoviesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Movies");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);
    }//GEN-LAST:event_MoviesbuttonActionPerformed

    private void NewestbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Newest");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_NewestbuttonActionPerformed

    private void SupportbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportbuttonActionPerformed
        javax.swing.JFrame page = new javax.swing.JFrame("Support");
        page.setSize(800, 600);
        page.setLocationRelativeTo(this);
        page.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        page.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_SupportbuttonActionPerformed

    private void MainsearchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MainsearchbarFocusGained
        if (Mainsearchbar.getText().trim().equals("Search in Rentify")) {
        Mainsearchbar.setText("");
          Mainsearchbar.setForeground(Color.BLACK);
    }

    }//GEN-LAST:event_MainsearchbarFocusGained

    private void MainsearchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MainsearchbarFocusLost
        if (Mainsearchbar.getText().trim().isEmpty()) {
        Mainsearchbar.setText("Search in Rentify");
         Mainsearchbar.setForeground(new Color(150, 150, 150));
    }

    }//GEN-LAST:event_MainsearchbarFocusLost

    private void MainsearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainsearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainsearchbarActionPerformed

    private void statuscomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuscomboboxActionPerformed
         if (sorter == null) return;

    String selected = statuscombobox.getSelectedItem().toString();

    if (selected.equalsIgnoreCase("All")) {
        sorter.setRowFilter(null);
    } else {
        sorter.setRowFilter(RowFilter.regexFilter("^" + Pattern.quote(selected) + "$", 3));
    }

    }//GEN-LAST:event_statuscomboboxActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        if (sorter == null) return;

    int expiryCol = 2; // 0=Item, 1=Rented on, 2=Expiry date, 3=Status

    sorter.setSortKeys(java.util.List.of(
        new javax.swing.RowSorter.SortKey(
            expiryCol,
            expiryAsc ? javax.swing.SortOrder.ASCENDING : javax.swing.SortOrder.DESCENDING
        )
    ));

    expiryAsc = !expiryAsc;
    sorter.sort();

    }//GEN-LAST:event_sortButtonActionPerformed

    private void mainsearchpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainsearchpanelMouseClicked
         performSearch();
    }//GEN-LAST:event_mainsearchpanelMouseClicked

    private void RentifylogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentifylogoMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        HomePage hm = new HomePage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RentifylogoMouseClicked

    private void LibrarybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        LibraryPage hm = new LibraryPage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LibrarybuttonMouseClicked

    private void BooksbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksbuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        BooksPage hm = new BooksPage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksbuttonMouseClicked

    private void MoviesbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesbuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        MoviePage hm = new MoviePage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MoviesbuttonMouseClicked

    private void NewestbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestbuttonMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        NewestPage hm = new NewestPage();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestbuttonMouseClicked

    private void SupportbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SupportbuttonMouseClicked

    private void ProfileiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileiconMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        UserDashboard hm = new UserDashboard();
        hm.setLocation(loc);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfileiconMouseClicked

    private void LibrarybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybuttonMouseEntered
        // TODO add your handling code here:
        Librarybutton.setBackground(new java.awt.Color(52, 115, 196));
        Librarybutton.setForeground(java.awt.Color.WHITE);
        Librarybutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Librarybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LibrarybuttonMouseEntered

    private void LibrarybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybuttonMouseExited
        // TODO add your handling code here:
        Librarybutton.setBackground(new java.awt.Color(232,241,253));
        Librarybutton.setForeground(new java.awt.Color(17,24,39));
        Librarybutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_LibrarybuttonMouseExited

    private void BooksbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksbuttonMouseEntered
        // TODO add your handling code here:
        Booksbutton.setBackground(new java.awt.Color(52, 115, 196));
        Booksbutton.setForeground(java.awt.Color.WHITE);
        Booksbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Booksbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BooksbuttonMouseEntered

    private void BooksbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksbuttonMouseExited
        // TODO add your handling code here:
        Booksbutton.setBackground(new java.awt.Color(232,241,253));
        Booksbutton.setForeground(new java.awt.Color(17,24,39));
        Booksbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_BooksbuttonMouseExited

    private void MoviesbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesbuttonMouseEntered
        // TODO add your handling code here:
        Moviesbutton.setBackground(new java.awt.Color(52, 115, 196));
        Moviesbutton.setForeground(java.awt.Color.WHITE);
        Moviesbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Moviesbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MoviesbuttonMouseEntered

    private void MoviesbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesbuttonMouseExited
        // TODO add your handling code here:
        Moviesbutton.setBackground(new java.awt.Color(232,241,253));
        Moviesbutton.setForeground(new java.awt.Color(17,24,39));
        Moviesbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_MoviesbuttonMouseExited

    private void NewestbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestbuttonMouseEntered
        // TODO add your handling code here:
        Newestbutton.setBackground(new java.awt.Color(52, 115, 196));
        Newestbutton.setForeground(java.awt.Color.WHITE);
        Newestbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Newestbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NewestbuttonMouseEntered

    private void NewestbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestbuttonMouseExited
        // TODO add your handling code here:
        Newestbutton.setBackground(new java.awt.Color(232,241,253));
        Newestbutton.setForeground(new java.awt.Color(17,24,39));
        Newestbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_NewestbuttonMouseExited

    private void SupportbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportbuttonMouseEntered
        // TODO add your handling code here:
        Supportbutton.setBackground(new java.awt.Color(52, 115, 196));
        Supportbutton.setForeground(java.awt.Color.WHITE);
        Supportbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        Supportbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SupportbuttonMouseEntered

    private void SupportbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportbuttonMouseExited
        // TODO add your handling code here:
        Supportbutton.setBackground(new java.awt.Color(232,241,253));
        Supportbutton.setForeground(new java.awt.Color(17,24,39));
        Supportbutton.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_SupportbuttonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalDate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Booksbutton;
    private javax.swing.JButton Librarybutton;
    private javax.swing.JTextField Mainsearchbar;
    private javax.swing.JButton Moviesbutton;
    private javax.swing.JButton Newestbutton;
    private javax.swing.JLabel Profileicon;
    private javax.swing.JLabel Rentifylogo;
    private javax.swing.JLabel Search_Icon;
    private javax.swing.JButton Supportbutton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainsearchpanel;
    private javax.swing.JTable rentalTable;
    private javax.swing.JScrollPane scrltable;
    private javax.swing.JButton sortButton;
    private javax.swing.JComboBox<String> statuscombobox;
    // End of variables declaration//GEN-END:variables
}
