/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author zenni
 */
public class reviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form reviewPanel
     */
    public reviewPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        review = new javax.swing.JTextField();
        rating = new javax.swing.JLabel();

        setLayout(null);

        username.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        username.setText("username");
        add(username);
        username.setBounds(20, 20, 101, 30);

        review.setText("review");
        review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewActionPerformed(evt);
            }
        });
        add(review);
        review.setBounds(20, 80, 941, 26);

        rating.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rating.setText("rating");
        add(rating);
        rating.setBounds(20, 50, 37, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void reviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel rating;
    private javax.swing.JTextField review;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
    public void setProduct(UserModel user) {
    username.setText(user.getProductName());
    review.setText(user.getProductPrice());
    ImageIcon icon = new ImageIcon(user.getProductImage());
    Image img = icon.getImage().getScaledInstance(100, 100,
    Image.SCALE_SMOOTH);
    image.setIcon(new ImageIcon(img));
}}
