/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import javax.swing.JPanel;
import model.ProductModel;
import model.User_model;

/**
 *
 * @author zenni
 */
public class SpecificProductPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SpecificProductPage.class.getName());

    /**
     * Creates new form productPage
     */
    public SpecificProductPage(int productId) {
        initComponents();
        setSize(1293,760);
        
        
        controller.ProductpageController controller = new controller.ProductpageController(this, productId);

            controller.loadProductById(productId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Profile_icon6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        productPanelPlace = new javax.swing.JPanel();
        reviewPanelPlace = new javax.swing.JPanel();
        rateBtn = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        Support = new javax.swing.JButton();
        Library = new javax.swing.JButton();
        Movies = new javax.swing.JButton();
        Newest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Books = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        logoBTN = new javax.swing.JLabel();
        profileBTN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));
        jPanel2.setLayout(null);

        Profile_icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Johnwickposter.jpg"))); // NOI18N
        jPanel2.add(Profile_icon6);
        Profile_icon6.setBounds(78, 578, 150, 150);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 560));

        productPanelPlace.setBackground(new java.awt.Color(255, 255, 255));
        productPanelPlace.setPreferredSize(new java.awt.Dimension(880, 200));

        reviewPanelPlace.setBackground(new java.awt.Color(255, 255, 255));
        reviewPanelPlace.setPreferredSize(new java.awt.Dimension(880, 220));

        rateBtn.setBackground(new java.awt.Color(255, 255, 255));
        rateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rateBtn.setForeground(new java.awt.Color(0, 0, 0));
        rateBtn.setText("Rate/Review product");
        rateBtn.setBorder(null);
        rateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reviewPanelPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateBtn)
                    .addComponent(productPanelPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productPanelPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewPanelPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 980, 560);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(25, 140, 1230, 565);

        jTextArea1.setBackground(new java.awt.Color(229, 231, 235));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jTextArea1);
        jTextArea1.setBounds(820, 100, 230, 30);

        Support.setBackground(new java.awt.Color(232, 241, 253));
        Support.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Support.setForeground(new java.awt.Color(17, 24, 39));
        Support.setText("Support");
        Support.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportActionPerformed(evt);
            }
        });
        jPanel1.add(Support);
        Support.setBounds(990, 50, 146, 36);

        Library.setBackground(new java.awt.Color(232, 241, 253));
        Library.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Library.setForeground(new java.awt.Color(17, 24, 39));
        Library.setText("Library");
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });
        jPanel1.add(Library);
        Library.setBounds(310, 50, 146, 36);

        Movies.setBackground(new java.awt.Color(232, 241, 253));
        Movies.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Movies.setForeground(new java.awt.Color(17, 24, 39));
        Movies.setText("Movies");
        Movies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesActionPerformed(evt);
            }
        });
        jPanel1.add(Movies);
        Movies.setBounds(650, 50, 146, 36);

        Newest.setBackground(new java.awt.Color(232, 241, 253));
        Newest.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Newest.setForeground(new java.awt.Color(17, 24, 39));
        Newest.setText("Newest");
        Newest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestActionPerformed(evt);
            }
        });
        jPanel1.add(Newest);
        Newest.setBounds(820, 50, 146, 36);

        jButton1.setBackground(new java.awt.Color(229, 231, 235));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1050, 100, 40, 30);

        Books.setBackground(new java.awt.Color(232, 241, 253));
        Books.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Books.setForeground(new java.awt.Color(17, 24, 39));
        Books.setText("Books");
        Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksActionPerformed(evt);
            }
        });
        jPanel1.add(Books);
        Books.setBounds(480, 50, 146, 36);

        cart.setBackground(new java.awt.Color(255, 255, 255));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        logoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        logoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoBTNMouseClicked(evt);
            }
        });
        jPanel1.add(logoBTN);
        logoBTN.setBounds(10, 10, 260, 70);

        profileBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N
        profileBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBTNMouseClicked(evt);
            }
        });
        jPanel1.add(profileBTN);
        profileBTN.setBounds(1180, 10, 85, 85);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupportActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LibraryActionPerformed

    private void MoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesActionPerformed

    private void NewestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BooksActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_cartActionPerformed

    private void rateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtnActionPerformed
        // TODO add your handling code here:
        ReviewPage page = new ReviewPage();
        page.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_rateBtnActionPerformed

    private void logoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBTNMouseClicked
        // TODO add your handling code here:
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoBTNMouseClicked

    private void profileBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBTNMouseClicked
        // TODO add your handling code here:
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SpecificProductPage(1).setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Books;
    private javax.swing.JButton Library;
    private javax.swing.JButton Movies;
    private javax.swing.JButton Newest;
    private javax.swing.JLabel Profile_icon6;
    private javax.swing.JButton Support;
    private javax.swing.JButton cart;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel logoBTN;
    private javax.swing.JPanel productPanelPlace;
    private javax.swing.JLabel profileBTN;
    private javax.swing.JButton rateBtn;
    private javax.swing.JPanel reviewPanelPlace;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getProductPanel(){
        return productPanelPlace;
    }
    
    public JPanel getReviewPanel(){
        return reviewPanelPlace;
    }
    
}
