/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DashboardController;
import java.awt.CardLayout;
import java.awt.Point;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JPanel;


/**
 *
 * @author zenni
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDashboard.class.getName());

    /**
     * Creates new form dashboard
     */
    public UserDashboard() {
        initComponents();
        setSize(1293,760);
        SearchBOX.getInputMap().put(
        javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
        "search");
        SearchBOX.getActionMap().put("search", new javax.swing.AbstractAction() {
            @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            performSearch();
            }
        });

        controller.DashboardController controller = new controller.DashboardController(this);
        
        

        controller.loadAllProducts();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProfileBTN = new javax.swing.JButton();
        OrdersBTN = new javax.swing.JButton();
        HistoryBTN = new javax.swing.JButton();
        WishlistBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        userEmail = new javax.swing.JLabel();
        userFullName = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JButton();
        Profile_icon9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productPanelReal = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        SupportBTN = new javax.swing.JButton();
        LibraryBTN = new javax.swing.JButton();
        MoviesBTN = new javax.swing.JButton();
        NewestBTN = new javax.swing.JButton();
        BooksBTN = new javax.swing.JButton();
        SearchBOX = new javax.swing.JTextArea();
        SearchBTN = new javax.swing.JButton();
        cart = new javax.swing.JButton();
        logoBTN = new javax.swing.JLabel();
        profileBTN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 250, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235), 3));

        ProfileBTN.setBackground(new java.awt.Color(250, 248, 248));
        ProfileBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        ProfileBTN.setForeground(new java.awt.Color(107, 114, 128));
        ProfileBTN.setText("Profile");
        ProfileBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        ProfileBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfileBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfileBTNMouseExited(evt);
            }
        });
        ProfileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileBTNActionPerformed(evt);
            }
        });

        OrdersBTN.setBackground(new java.awt.Color(250, 248, 248));
        OrdersBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        OrdersBTN.setForeground(new java.awt.Color(107, 114, 128));
        OrdersBTN.setText("Orders");
        OrdersBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        OrdersBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrdersBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrdersBTNMouseExited(evt);
            }
        });
        OrdersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersBTNActionPerformed(evt);
            }
        });

        HistoryBTN.setBackground(new java.awt.Color(250, 248, 248));
        HistoryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        HistoryBTN.setForeground(new java.awt.Color(107, 114, 128));
        HistoryBTN.setText("History");
        HistoryBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        HistoryBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoryBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistoryBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistoryBTNMouseExited(evt);
            }
        });
        HistoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryBTNActionPerformed(evt);
            }
        });

        WishlistBTN.setBackground(new java.awt.Color(250, 248, 248));
        WishlistBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        WishlistBTN.setForeground(new java.awt.Color(107, 114, 128));
        WishlistBTN.setText("Wishlist");
        WishlistBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 166, 154)));
        WishlistBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WishlistBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WishlistBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WishlistBTNMouseExited(evt);
            }
        });
        WishlistBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WishlistBTNActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 560));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userEmail.setForeground(new java.awt.Color(51, 51, 51));
        userEmail.setText("ashishshrestha250@gmail.com");

        userFullName.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        userFullName.setForeground(new java.awt.Color(51, 51, 51));
        userFullName.setText("Ashish Shrestha");

        LogoutBTN.setBackground(new java.awt.Color(38, 166, 154));
        LogoutBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LogoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBTN.setText("Logout");
        LogoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseExited(evt);
            }
        });
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        Profile_icon9.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        Profile_icon9.setForeground(new java.awt.Color(51, 51, 51));
        Profile_icon9.setText("Favourites");

        productPanelReal.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(productPanelReal);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WishlistBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HistoryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrdersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(icon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userFullName)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(userEmail)))
                        .addContainerGap(456, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Profile_icon9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ProfileBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(OrdersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(HistoryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(WishlistBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userEmail))
                    .addComponent(icon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Profile_icon9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(25, 140, 1230, 565);

        SupportBTN.setBackground(new java.awt.Color(232, 241, 253));
        SupportBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        SupportBTN.setForeground(new java.awt.Color(17, 24, 39));
        SupportBTN.setText("Support");
        SupportBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SupportBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SupportBTNMouseExited(evt);
            }
        });
        SupportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SupportBTN);
        SupportBTN.setBounds(990, 50, 146, 36);

        LibraryBTN.setBackground(new java.awt.Color(232, 241, 253));
        LibraryBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        LibraryBTN.setForeground(new java.awt.Color(17, 24, 39));
        LibraryBTN.setText("Library");
        LibraryBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LibraryBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LibraryBTNMouseExited(evt);
            }
        });
        LibraryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LibraryBTN);
        LibraryBTN.setBounds(310, 50, 146, 36);

        MoviesBTN.setBackground(new java.awt.Color(232, 241, 253));
        MoviesBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        MoviesBTN.setForeground(new java.awt.Color(17, 24, 39));
        MoviesBTN.setText("Movies");
        MoviesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MoviesBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MoviesBTNMouseExited(evt);
            }
        });
        MoviesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesBTNActionPerformed(evt);
            }
        });
        jPanel1.add(MoviesBTN);
        MoviesBTN.setBounds(650, 50, 146, 36);

        NewestBTN.setBackground(new java.awt.Color(232, 241, 253));
        NewestBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        NewestBTN.setForeground(new java.awt.Color(17, 24, 39));
        NewestBTN.setText("Newest");
        NewestBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewestBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NewestBTNMouseExited(evt);
            }
        });
        NewestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewestBTNActionPerformed(evt);
            }
        });
        jPanel1.add(NewestBTN);
        NewestBTN.setBounds(820, 50, 146, 36);

        BooksBTN.setBackground(new java.awt.Color(232, 241, 253));
        BooksBTN.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        BooksBTN.setForeground(new java.awt.Color(17, 24, 39));
        BooksBTN.setText("Books");
        BooksBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksBTNMouseExited(evt);
            }
        });
        BooksBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BooksBTN);
        BooksBTN.setBounds(480, 50, 146, 36);

        SearchBOX.setBackground(new java.awt.Color(243, 243, 243));
        SearchBOX.setColumns(20);
        SearchBOX.setRows(5);
        SearchBOX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(SearchBOX);
        SearchBOX.setBounds(820, 100, 230, 30);

        SearchBTN.setBackground(new java.awt.Color(243, 243, 243));
        SearchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon.png"))); // NOI18N
        SearchBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(SearchBTN);
        SearchBTN.setBounds(1050, 100, 40, 30);

        cart.setBackground(new java.awt.Color(249, 250, 251));
        cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cart40x40.png"))); // NOI18N
        cart.setBorder(null);
        cart.setFocusPainted(false);
        cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartActionPerformed(evt);
            }
        });
        jPanel1.add(cart);
        cart.setBounds(1100, 100, 40, 40);

        logoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/rentifyohnebg (1).png"))); // NOI18N
        logoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoBTNMouseClicked(evt);
            }
        });
        jPanel1.add(logoBTN);
        logoBTN.setBounds(10, 10, 260, 70);

        profileBTN.setBackground(new java.awt.Color(249, 250, 251));
        profileBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile-85x85.png"))); // NOI18N
        profileBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBTNMouseClicked(evt);
            }
        });
        jPanel1.add(profileBTN);
        profileBTN.setBounds(1180, 10, 85, 85);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean containsText(java.awt.Component comp, String text) {
    // If this component has text (e.g. JLabel, JButton, JTextComponent)
    if (comp instanceof javax.swing.JLabel) {
        String labelText = ((javax.swing.JLabel) comp).getText();
        if (labelText != null && labelText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.JButton) {
        String btnText = ((javax.swing.JButton) comp).getText();
        if (btnText != null && btnText.toLowerCase().contains(text)) {
            return true;
        }
    } else if (comp instanceof javax.swing.text.JTextComponent) {
        String fieldText = ((javax.swing.text.JTextComponent) comp).getText();
        if (fieldText != null && fieldText.toLowerCase().contains(text)) {
            return true;
        }
    }

    // If it's a container (like JPanel), search its children
    if (comp instanceof java.awt.Container) {
        for (java.awt.Component child : ((java.awt.Container) comp).getComponents()) {
            if (containsText(child, text)) {
                return true;
            }
        }
    }
    return false;
}

    private void performSearch() {
    String text = SearchBOX.getText().trim().toLowerCase();
    boolean showAll = text.isEmpty();

    for (java.awt.Component comp : jPanel2.getComponents()) {
        boolean visible = showAll;

        if (!showAll) {
            // Search in all child components' text
            visible = containsText(comp, text);
        }
        comp.setVisible(visible);
    }

    jPanel2.revalidate();
    jPanel2.repaint();
}
    private void ProfileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileBTNActionPerformed

    private void OrdersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersBTNActionPerformed

    private void HistoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryBTNActionPerformed

    private void WishlistBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WishlistBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WishlistBTNActionPerformed

    private void SupportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupportBTNActionPerformed

    private void LibraryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        LibraryPage libraryPage = new LibraryPage();
        libraryPage.setLocation(loc);
        libraryPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LibraryBTNActionPerformed

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        Login log = new Login();
        log.setLocation(loc);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void MoviesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesBTNActionPerformed
        // TODO add your handling code here:
    // Navigate to Profile Page
        Point loc = this.getLocation();
        MoviePage moviePage = new MoviePage();
        moviePage.setLocation(loc);
        moviePage.setVisible(true);
        this.dispose(); // Close current dashboard

    }//GEN-LAST:event_MoviesBTNActionPerformed

    private void NewestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewestBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        NewestPage newestPage = new NewestPage();
        newestPage.setLocation(loc);
        newestPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NewestBTNActionPerformed

    private void BooksBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksBTNActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        BooksPage booksPage = new BooksPage();
        booksPage.setLocation(loc);
        booksPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BooksBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        // TODO add your handling code here:
        performSearch();
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cartActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed

        // TODO add your handling code here:
        Point loc = this.getLocation();
        manageproducts manageproductsPage = new manageproducts();
        manageproductsPage.setLocation(loc);
        manageproductsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        Point loc = this.getLocation();
        UserDashboard productPage = new UserDashboard();
        productPage.setLocation(loc);
        productPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userActionPerformed

    private void logoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        HomePage homePage = new HomePage();
        homePage.setLocation(loc);
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoBTNMouseClicked

    private void profileBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setLocation(loc);
        userDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileBTNMouseClicked

    private void LibraryBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibraryBTNMouseEntered
        // TODO add your handling code here:
        LibraryBTN.setBackground(new java.awt.Color(52, 115, 196));
        LibraryBTN.setForeground(java.awt.Color.WHITE);
        LibraryBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        LibraryBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LibraryBTNMouseEntered

    private void LibraryBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibraryBTNMouseExited
        // TODO add your handling code here:
        LibraryBTN.setBackground(new java.awt.Color(232,241,253));
        LibraryBTN.setForeground(new java.awt.Color(17,24,39));
        LibraryBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_LibraryBTNMouseExited

    private void BooksBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksBTNMouseEntered
        // TODO add your handling code here:
        BooksBTN.setBackground(new java.awt.Color(52, 115, 196));
        BooksBTN.setForeground(java.awt.Color.WHITE);
        BooksBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        BooksBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BooksBTNMouseEntered

    private void BooksBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksBTNMouseExited
        // TODO add your handling code here:
        BooksBTN.setBackground(new java.awt.Color(232,241,253));
        BooksBTN.setForeground(new java.awt.Color(17,24,39));
        BooksBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_BooksBTNMouseExited

    private void MoviesBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesBTNMouseEntered
        // TODO add your handling code here:
        MoviesBTN.setBackground(new java.awt.Color(52, 115, 196));
        MoviesBTN.setForeground(java.awt.Color.WHITE);
        MoviesBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        MoviesBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_MoviesBTNMouseEntered

    private void MoviesBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoviesBTNMouseExited
        // TODO add your handling code here:
        MoviesBTN.setBackground(new java.awt.Color(232,241,253));
        MoviesBTN.setForeground(new java.awt.Color(17,24,39));
        MoviesBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_MoviesBTNMouseExited

    private void NewestBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestBTNMouseEntered
        // TODO add your handling code here:
        NewestBTN.setBackground(new java.awt.Color(52, 115, 196));
        NewestBTN.setForeground(java.awt.Color.WHITE);
        NewestBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        NewestBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_NewestBTNMouseEntered

    private void NewestBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewestBTNMouseExited
        // TODO add your handling code here:
        NewestBTN.setBackground(new java.awt.Color(232,241,253));
        NewestBTN.setForeground(new java.awt.Color(17,24,39));
        NewestBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_NewestBTNMouseExited

    private void SupportBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportBTNMouseEntered
        // TODO add your handling code here:
        SupportBTN.setBackground(new java.awt.Color(52, 115, 196));
        SupportBTN.setForeground(java.awt.Color.WHITE);
        SupportBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(40, 90, 150), 2)
        );
        SupportBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_SupportBTNMouseEntered

    private void SupportBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupportBTNMouseExited
        // TODO add your handling code here:
        SupportBTN.setBackground(new java.awt.Color(232,241,253));
        SupportBTN.setForeground(new java.awt.Color(17,24,39));
        SupportBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(194,194,194), 1)
        );
    }//GEN-LAST:event_SupportBTNMouseExited

    private void ProfileBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileBTNMouseEntered
        // TODO add your handling code here:
        ProfileBTN.setBackground(new java.awt.Color(38,166,154));
        ProfileBTN.setForeground(java.awt.Color.WHITE);
        ProfileBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
        );
        ProfileBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_ProfileBTNMouseEntered

    private void ProfileBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileBTNMouseExited
        // TODO add your handling code here:
        ProfileBTN.setBackground(new java.awt.Color(250,248,248));
        ProfileBTN.setForeground(new java.awt.Color(107,114,128));
        ProfileBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 1)
        );
    }//GEN-LAST:event_ProfileBTNMouseExited

    private void OrdersBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersBTNMouseEntered
        // TODO add your handling code here:
        OrdersBTN.setBackground(new java.awt.Color(38,166,154));
        OrdersBTN.setForeground(java.awt.Color.WHITE);
        OrdersBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
        );
        OrdersBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_OrdersBTNMouseEntered

    private void OrdersBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersBTNMouseExited
        // TODO add your handling code here:
        OrdersBTN.setBackground(new java.awt.Color(250,248,248));
        OrdersBTN.setForeground(new java.awt.Color(107,114,128));
        OrdersBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 1)
        );
    }//GEN-LAST:event_OrdersBTNMouseExited

    private void HistoryBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryBTNMouseEntered
        // TODO add your handling code here:
        HistoryBTN.setBackground(new java.awt.Color(38,166,154));
        HistoryBTN.setForeground(java.awt.Color.WHITE);
        HistoryBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
        );
        HistoryBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_HistoryBTNMouseEntered

    private void HistoryBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryBTNMouseExited
        // TODO add your handling code here:
        HistoryBTN.setBackground(new java.awt.Color(250,248,248));
        HistoryBTN.setForeground(new java.awt.Color(107,114,128));
        HistoryBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 1)
        );
    }//GEN-LAST:event_HistoryBTNMouseExited

    private void WishlistBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WishlistBTNMouseEntered
        // TODO add your handling code here:
        WishlistBTN.setBackground(new java.awt.Color(38,166,154));
        WishlistBTN.setForeground(java.awt.Color.WHITE);
        WishlistBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
        );
        WishlistBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_WishlistBTNMouseEntered

    private void WishlistBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WishlistBTNMouseExited
        // TODO add your handling code here:
        WishlistBTN.setBackground(new java.awt.Color(250,248,248));
        WishlistBTN.setForeground(new java.awt.Color(107,114,128));
        WishlistBTN.setBorder(
            BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 1)
        );
    }//GEN-LAST:event_WishlistBTNMouseExited

    private void LogoutBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseEntered
        // TODO add your handling code here:
        LogoutBTN.setBackground(new java.awt.Color(38,166,154)); 
        LogoutBTN.setForeground(java.awt.Color.WHITE);
        LogoutBTN.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(38,166,154), 2)
    );
        LogoutBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_LogoutBTNMouseEntered

    private void LogoutBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseExited
        // TODO add your handling code here:
        LogoutBTN.setBackground(new java.awt.Color(38,166,154)); 
        LogoutBTN.setForeground(new java.awt.Color(255,255,255));
        LogoutBTN.setBorder(
        BorderFactory.createLineBorder(new java.awt.Color(193,193,193), 2)
        );
    }//GEN-LAST:event_LogoutBTNMouseExited

    private void ProfileBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        this.dispose();

        UserDashboard ad = new UserDashboard();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_ProfileBTNMouseClicked

    private void OrdersBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersBTNMouseClicked

    private void HistoryBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        this.dispose();

        Purchasehistory ad = new Purchasehistory();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_HistoryBTNMouseClicked

    private void WishlistBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WishlistBTNMouseClicked
        // TODO add your handling code here:
        Point loc = this.getLocation();
        this.dispose();

        Cart ad = new Cart();
        ad.setLocation(loc);
        ad.setVisible(true);
    }//GEN-LAST:event_WishlistBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BooksBTN;
    private javax.swing.JButton HistoryBTN;
    private javax.swing.JButton LibraryBTN;
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JButton MoviesBTN;
    private javax.swing.JButton NewestBTN;
    private javax.swing.JButton OrdersBTN;
    private javax.swing.JButton ProfileBTN;
    private javax.swing.JLabel Profile_icon9;
    private javax.swing.JTextArea SearchBOX;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton SupportBTN;
    private javax.swing.JButton WishlistBTN;
    private javax.swing.JButton cart;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoBTN;
    private javax.swing.JPanel productPanelReal;
    private javax.swing.JLabel profileBTN;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userFullName;
    // End of variables declaration//GEN-END:variables
   
    
    
    public JPanel getProductPanel(){
        return productPanelReal;
    }
  
}
