/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class wishlist extends javax.swing.JPanel {

    /**
     * Creates new form wishlist
     */
    public wishlist() {
        initComponents();
        
        ContentPanel.setLayout(new java.awt.CardLayout());
        
        ContentPanel.add(ProfilePanel, "Profile");
        ContentPanel.add(OrderPanel, "Order");
        ContentPanel.add(HistoryPanel, "History");
        ContentPanel.add(WishlistPanel, "Wishlist");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        libraryBTN = new javax.swing.JButton();
        bookbutton = new javax.swing.JButton();
        Moviesbtn = new javax.swing.JButton();
        newestbtn = new javax.swing.JButton();
        supportbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonpanel = new javax.swing.JPanel();
        Profile = new javax.swing.JButton();
        Orders = new javax.swing.JButton();
        History = new javax.swing.JButton();
        Wishlist = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        OrderPanel = new javax.swing.JPanel();
        HistoryPanel = new javax.swing.JPanel();
        WishlistPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(249, 250, 251));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rentify-200.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(20, 10, 200, 70);

        libraryBTN.setBackground(new java.awt.Color(232, 241, 253));
        libraryBTN.setText("Library");
        libraryBTN.setPreferredSize(new java.awt.Dimension(156, 36));
        libraryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryBTNActionPerformed(evt);
            }
        });
        add(libraryBTN);
        libraryBTN.setBounds(310, 30, 156, 36);

        bookbutton.setBackground(new java.awt.Color(232, 241, 253));
        bookbutton.setText("Books");
        bookbutton.setPreferredSize(new java.awt.Dimension(136, 136));
        bookbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookbuttonMouseClicked(evt);
            }
        });
        bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbuttonActionPerformed(evt);
            }
        });
        add(bookbutton);
        bookbutton.setBounds(490, 30, 156, 36);

        Moviesbtn.setBackground(new java.awt.Color(232, 241, 253));
        Moviesbtn.setText("Movies");
        Moviesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoviesbtnActionPerformed(evt);
            }
        });
        add(Moviesbtn);
        Moviesbtn.setBounds(670, 30, 156, 36);

        newestbtn.setBackground(new java.awt.Color(232, 241, 253));
        newestbtn.setText("Newest");
        newestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newestbtnActionPerformed(evt);
            }
        });
        add(newestbtn);
        newestbtn.setBounds(850, 30, 156, 36);

        supportbtn.setBackground(new java.awt.Color(232, 241, 253));
        supportbtn.setText("Support");
        supportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportbtnActionPerformed(evt);
            }
        });
        add(supportbtn);
        supportbtn.setBounds(1030, 30, 156, 36);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(1210, 10, 62, 62);

        buttonpanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Profile.setText("Profile");
        Profile.setPreferredSize(new java.awt.Dimension(179, 36));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        Orders.setText("Orders");
        Orders.setPreferredSize(new java.awt.Dimension(179, 36));
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });

        History.setText("History");
        History.setPreferredSize(new java.awt.Dimension(179, 36));
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });

        Wishlist.setText("Wishlist");
        Wishlist.setPreferredSize(new java.awt.Dimension(179, 36));
        Wishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WishlistActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(38, 166, 154));
        Logout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Log out");

        javax.swing.GroupLayout buttonpanelLayout = new javax.swing.GroupLayout(buttonpanel);
        buttonpanel.setLayout(buttonpanelLayout);
        buttonpanelLayout.setHorizontalGroup(
            buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wishlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        buttonpanelLayout.setVerticalGroup(
            buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Wishlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        add(buttonpanel);
        buttonpanel.setBounds(30, 120, 250, 565);

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        ContentPanel.add(ProfilePanel, "card2");

        javax.swing.GroupLayout OrderPanelLayout = new javax.swing.GroupLayout(OrderPanel);
        OrderPanel.setLayout(OrderPanelLayout);
        OrderPanelLayout.setHorizontalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        OrderPanelLayout.setVerticalGroup(
            OrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        ContentPanel.add(OrderPanel, "card2");

        javax.swing.GroupLayout HistoryPanelLayout = new javax.swing.GroupLayout(HistoryPanel);
        HistoryPanel.setLayout(HistoryPanelLayout);
        HistoryPanelLayout.setHorizontalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        HistoryPanelLayout.setVerticalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        ContentPanel.add(HistoryPanel, "card2");

        WishlistPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WishlistPanelLayout = new javax.swing.GroupLayout(WishlistPanel);
        WishlistPanel.setLayout(WishlistPanelLayout);
        WishlistPanelLayout.setHorizontalGroup(
            WishlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        WishlistPanelLayout.setVerticalGroup(
            WishlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        ContentPanel.add(WishlistPanel, "card2");

        add(ContentPanel);
        ContentPanel.setBounds(280, 120, 970, 565);
    }// </editor-fold>//GEN-END:initComponents

    private void libraryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryBTNActionPerformed
        javax.swing.JFrame f = new javax.swing.JFrame("Library");

        f.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f.getContentPane().add(new LibraryPanel());
        f.pack();
        f.setLocationRelativeTo(this);
        f.setVisible(true);
    }//GEN-LAST:event_libraryBTNActionPerformed

    private void bookbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookbuttonMouseClicked

    private void bookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbuttonActionPerformed
        javax.swing.JFrame f = new javax.swing.JFrame("Books");

        f.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f.getContentPane().add(new BookPanel());
        f.pack();
        f.setLocationRelativeTo(this);
        f.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_bookbuttonActionPerformed

    private void MoviesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoviesbtnActionPerformed
        javax.swing.JFrame f = new javax.swing.JFrame("Movies");

        f.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f.getContentPane().add(new MoviesPanel());
        f.pack();
        f.setLocationRelativeTo(this);
        f.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_MoviesbtnActionPerformed

    private void newestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newestbtnActionPerformed
        javax.swing.JFrame f = new javax.swing.JFrame("Newest");

        f.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f.getContentPane().add(new NewestPanel());
        f.pack();
        f.setLocationRelativeTo(this);
        f.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_newestbtnActionPerformed

    private void supportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportbtnActionPerformed
        javax.swing.JFrame f = new javax.swing.JFrame("Support");

        f.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        f.getContentPane().add(new SupportPanel());
        f.pack();
        f.setLocationRelativeTo(this);
        f.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_supportbtnActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)ContentPanel.getLayout();
        card.show(ContentPanel, "History");
        // TODO add your handling code here:
    }//GEN-LAST:event_HistoryActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)ContentPanel.getLayout();
        card.show(ContentPanel, "Profile");
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)ContentPanel.getLayout();
        card.show(ContentPanel, "Orders");
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersActionPerformed

    private void WishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WishlistActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)ContentPanel.getLayout();
        card.show(ContentPanel, "Wishlist");
        // TODO add your handling code here:
    }//GEN-LAST:event_WishlistActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JButton History;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Moviesbtn;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JButton Orders;
    private javax.swing.JButton Profile;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JButton Wishlist;
    private javax.swing.JPanel WishlistPanel;
    private javax.swing.JButton bookbutton;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton libraryBTN;
    private javax.swing.JButton newestbtn;
    private javax.swing.JButton supportbtn;
    // End of variables declaration//GEN-END:variables
}
